modules:
        #cloudatlas:
        default:
            # Available collectors are bmc, ipmi, chassis, dcmi, sel, and sm-lan-mode
            collectors:
            - bmc
            - ipmi
            - dcmi
            - chassis
            - sel
            collector_cmd:
                bmc: sudo
                ipmi: sudo
                dcmi: sudo
                chassis: sudo
                sel: sudo
            custom_args:
                bmc:
                - "bmc-info"
                ipmi:
                - "ipmimonitoring"
                dcmi:
                - "ipmi-dcmi"
                chassis:
                - "ipmi-chassis"
                sel:
                - "ipmi-sel"
